=== madcampos/sdrlog/src/data/$schemas/data.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "7a61ffa0-4170-47ba-994d-1e470412c8ad",
	"type": "object",
	"required": ["category", "type", "sku", "name", "description", "edition", "publisher", "originalLanguage", "gameDate", "status", "cover"],
	"definitions": {
		"locale-code": {
			"type": "string",
			"pattern": "^(?:art-lojban|cel-gaulish|no-bok|no-nyn|zh-guoyu|zh-hakka|zh-min|zh-min-nan|zh-xiang|en-GB-oed|i-ami|i-bnn|i-default|i-enochian|i-hak|i-klingon|i-lux|i-mingo|i-navajo|i-pwn|i-tao|i-tay|i-tsu|sgn-BE-FR|sgn-BE-NL|sgn-CH-DE|(?:x(?:-[A-Za-z0-9]{1,8})+)|(?:(?:(?:[A-Za-z]{2,3}(?:-[A-Za-z]{3}(?:-[A-Za-z]{3}){0,2})?)|[A-Za-z]{4}|[A-Za-z]{5,8})(?:-[A-Za-z]{4})?(?:-[A-Za-z]{2}|[0-9]{3})?(?:-[A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3})*(?:-[0-9A-WY-Za-wy-z](?:-[A-Za-z0-9]{2,8})+)*(?:-x(?:-[A-Za-z0-9]{1,8})+)?))$"
		},
		"sku": { "type": "string", "pattern": "^[A-Z0-9](?:-?[A-Z0-9])+(?:-[A-Z])?$" },
		"publisher": {
			"enum": [
				"Catalyst Game Labs",
				"Cliffhanger Productions",
				"FASA Corporation",
				"Fantasy Productions",
				"Harebrained Schemes",
				"Pegasus Spiele",
				"WizKids Games",
				"Heyne Verlag",
				"Other",
				"Unofficial"
			]
		},
		"absolute-link": { "type": "string", "format": "uri" },
		"relative-link": { "type": "string", "format": "iri" },
		"category": { "enum": ["rulebook", "sourcebook", "mission", "magazine", "novel", "videogame", "tcg", "boardgame", "misc"] },
		"type": { "enum": ["digital", "print", "scan", "ocr", "physical"] },
		"sku-list": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "$ref": "#/definitions/sku" } },
		"name": { "type": "string" },
		"names": { "type": "object", "propertyNames": { "$ref": "#/definitions/locale-code" }, "additionalProperties": { "type": "string", "minLength": 1 }, "minProperties": 1 },
		"description": { "type": "string", "minLength": 1 },
		"edition": { "type": "integer", "minimum": 1, "maximum": 6 },
		"publisher-list": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "$ref": "#/definitions/publisher" } },
		"game-date": { "type": "string", "pattern": "^[0-9]{4}-[0-9]{2}$" },
		"release-date": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "type": "string", "format": "date" } },
		"status": { "enum": ["missing", "outofscope", "canceled", "ok", "partially-missing"] },
		"original-language": { "$ref": "#/definitions/locale-code" },
		"notes": { "type": "string", "minLength": 1 },
		"links": { "type": "object", "propertyNames": { "$ref": "#/definitions/absolute-link" }, "additionalProperties": { "type": "string", "minLength": 1 }, "minProperties": 1 }
	},
	"properties": {
		"category": { "$ref": "#/definitions/category" },
		"type": { "$ref": "#/definitions/type" },
		"sku": { "$ref": "#/definitions/sku-list" },
		"name": { "$ref": "#/definitions/name" },
		"names": { "$ref": "#/definitions/names" },
		"description": { "$ref": "#/definitions/description" },
		"edition": { "$ref": "#/definitions/edition" },
		"publisher": { "$ref": "#/definitions/publisher-list" },
		"gameDate": { "$ref": "#/definitions/game-date" },
		"releaseDate": { "$ref": "#/definitions/release-date" },
		"status": { "$ref": "#/definitions/status" },
		"originalLanguage": { "$ref": "#/definitions/original-language" },
		"notes": { "$ref": "#/definitions/notes" },
		"links": { "$ref": "#/definitions/links" },
		"subItems": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"name": { "$ref": "#/definitions/name" },
					"status": { "$ref": "#/definitions/status" },
					"description": { "$ref": "#/definitions/description" },
					"notes": { "$ref": "#/definitions/notes" },
					"links": { "$ref": "#/definitions/links" }
				}
			}
		},
		"cover": { "$ref": "#/definitions/relative-link" }
	}
}

=== madcampos/sdrlog/public/data/27485/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["27485", "45045"],
	"name": "Boundless Mercy",
	"category": "mission",
	"type": "digital",
	"names": { "de-DE": "Gnade ohne Grenzen" },
	"originalLanguage": "en-US",
	"description": "Elizabeth Nunn, a delightful woman who happens to have an odd habit of hanging out in hospitals and abandoned churches, has a grudge. A deep grudge. The kind of grudge that requires professional help to work out, and we're not talking about a psychotherapist. She needs shadowrunners, and if they're willing to take on the job, they'll encounter fierce gangers, wild critters, and members of a secret magical society who fiercely guard their mysteries. If the runners can survive, they can find out just what Nunn is mad aboutâ€”and how far she is willing to go for her revenge.",
	"edition": 5,
	"publisher": ["Catalyst Game Labs", "Pegasus Spiele"],
	"releaseDate": ["2015-10-16", "2016-12-01"],
	"gameDate": "2077-08",
	"notes": "The German edition also has a summary of \"Montreal 2074\".",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/AUG002/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["AUG002"],
	"name": "Augment 02 [Summer 2083]",
	"category": "magazine",
	"type": "digital",
	"originalLanguage": "en",
	"description": "Augment is Shadowrunâ€™s official magazine. This is a fully in-universe publication, and can be used in Shadowrun games as well as enjoyed by the casual reader.\n\nAugment, Summer 2083. The Matrix is magic, and Augment proves it in this issue. Discover the newest deck to hit the market while listening to Ares VP Karen King and Marques Reille go toe-to-toe. Art Director Denidra Boann shares her insights into the art of the page as Hunter Cobb continues to follow the story behind the Tailgate Riots in Denver! Enjoy reviews of new products, clothing, tech, and so much more!\n\nAugment your life with Augment magazine!",
	"edition": 6,
	"publisher": ["Catalyst Game Labs"],
	"releaseDate": ["2025-05-16"],
	"gameDate": "2082-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/26002A/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["26002A", "46010", "SR08"],
	"name": "Augmentation",
	"category": "rulebook",
	"type": "digital",
	"names": { "de-DE": "BodyTech", "fr-FR": "Augmentations", "jp-JP": "ーグメンテーショオン" },
	"originalLanguage": "en-US",
	"description": "The Shadows Have Evolved\n\nThe year is 2070. The world is not only Awakened—-it's wired. Cyber and bioware implants make your meat body better-than-flesh, while the wireless Matrix enhances your perceptions with hyper-real senses. Deals are made in steel and lead more often than gold or nuyen; success and failure live only a razor's edge apart. Creatures of myth and legend walk the streets, while the arcane skills of spellslingers are in high demand. Above it all, monolithic megacorps bleed the world dry, sabotaging each other in covert cutthroat competition as they go to war over the bottom line.\n\nYou're a shadowrunner, a street operative, scratching out a living on the mean sprawl streets. You may be human, elf, dwarf, ork or troll. From lethal street samurai to well-connected info brokers, spell-slinging mages or code-cracking hackers. No matter what, you're a professional corporate pawn or \"deniable asset,\" you get the job done.\n\nShadowrun, Fourth Edition offers a completely new rules system that is simple, integrated and accessible. The state-of-the-art has also been advanced, introducing a new level of augmented reality, new gear, new magical discoveries, and more.\n\nThis hardcover rulebook contains all the rules gamemasters and players need to create characters and ongoing adventures set in the popular Shadowrun universe. Note that the Shadowrun, Fourth Edition will replace the Shadowrun, Third Edition rules set. Source material from previous editions will still be compatible.",
	"edition": 4,
	"publisher": ["Catalyst Game Labs", "Other", "Pegasus Spiele"],
	"releaseDate": ["2008-08-23", "2009-01-01", "2011-01-01"],
	"gameDate": "2070-08",
	"notes": "The German \"Bodytech\" contains the latest errata for \"augmentation\" as well as 5 additional cybersuites (which are twice as many as in the original).",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/28300/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["28300"],
	"name": "Cutting Black",
	"category": "mission",
	"type": "digital",
	"names": { "de-DE": "Blackout" },
	"originalLanguage": "en-US",
	"description": "TOTAL DARK\n\nVoice scream in the darkness. Voices of the lost drift through the night. Their sound is despair, sorrow, and terror. The noise grinds at your soul, but only thing worse than listening to the chorus of pain is joining it.\nThe world is changing. Desperate times require desperate measures, and the ground beneath your feet will shake when those measures are meted out. Hold on, buckle up, and try to survive. Parts of the world are cutting to blackâ€”so keep your guard up, be prepared, and don't let the dark consume you.\nCutting Black is a campaign book to help launch players and gamemasters into Shadowrun, Sixth World. With breaking news and world-shaking events, it provides material to carry players through months of games. If they can survive that long.",
	"edition": 6,
	"publisher": ["Catalyst Game Labs", "Pegasus Spiele"],
	"releaseDate": ["2020-02-01"],
	"gameDate": "2080-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/482D5/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["482D5"],
	"name": "Datapuls: SOTA 2082",
	"category": "sourcebook",
	"type": "digital",
	"originalLanguage": "de-DE",
	"description": "# Von Knarren und Kähnen\n\nDie Uhr dreht sich weiter, sie bleibt niemals stehen. Und mit ihr läuft auch die Technik in die Zukunft - mit oder ohne dich. Wenn du am Ball bleiben willst, solltest du dich informieren: Du solltest die neuesten Schießeisen kennen, die coolesten Drohnen besitzen oder das schnellste Auto fahren. Oder zumindest eines, das schneller ist als die Polizei.\n\nDatapuls SOTA 2082 wirft ein Licht auf neue Ausrüstung für Shadowrun. Präsentiert werden neue und alte Waffen, Autos, Motorräder, Flugplattformen und Kampfdrohnen, mit denen sich die Runner ausrüsten können oder denen sie sich entgegenstellen müssen. Zudem enthält das PDF neue Schutzgeister für magisch Erwachte und die Beschreibungen einiger Schattengrößen.",
	"edition": 6,
	"publisher": ["Pegasus Spiele"],
	"releaseDate": ["2020-04-28"],
	"gameDate": "2082-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/7202/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["7202"],
	"name": "Native American Nations Volume One",
	"category": "sourcebook",
	"type": "scan",
	"originalLanguage": "en-US",
	"description": "Over thirty years ago, the violent formation of the Native American Nations shattered the United States of America and altered the geo-political boundaries of North America. Now, someone's setting out to prove that turn-about is not fair play and to bring about a little change of their own. Is it payback? Or something deeper? Regardless, it's a mad chase through the Native American Nations, full of the chaos one expects in a Shadowrun adventure.",
	"edition": 1,
	"publisher": ["FASA Corporation", "Catalyst Game Labs"],
	"releaseDate": ["1991-05-01", "2015-03-11"],
	"gameDate": "2051-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/KS001/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["KS001"],
	"name": "Shadowrun: Sprawl Ops",
	"category": "boardgame",
	"type": "physical",
	"originalLanguage": "en-US",
	"description": "In Shadowrun: Sprawl Ops, players lead a team of shadowrunners gunning for the big score!\nAlong the way they'll have the chance to hire more seasoned runners, outfit their team with cutting-edge technology—from the latest weapons to cyberware enhancements—and take on increasingly dangerous contracts on the mean streets of the Seattle Metroplex.\nEach payout increases your chances for a more lethal combination of gear, training, and skill. All leading to that final score as you take on one of the world's megacorporations. But you've got to hit it before another team steals your ticket to the big time—hold off too long to grab that ring, and you'll lose it all!",
	"edition": 5,
	"publisher": ["Catalyst Game Labs"],
	"releaseDate": ["2019-06-01"],
	"gameDate": "2075-01",
	"status": "outofscope",
	"notes": "Announced as a kickstarter campaign. Possible a retake on Hostile Takeover.",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/PRO866/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["PRO866"],
	"name": "Jetzt oder nie",
	"category": "mission",
	"type": "digital",
	"originalLanguage": "de-DE",
	"description": "Einmalige Gelegenheit!\n\nAm Schwarzen Valentinstag 2083 verwüstet die Detonation von 235 unterirdischen Sprengladungen weite Teile des Rhein-Ruhr-Megaplexes. Zehntausende sind tot, Hunderttausende auf der Flucht vor dem Jahrhundertwinter 2082/83, Ordnung und Abläufe sind großflächig zusammengebrochen. Katastrophal für die einen – aber eine einmalige Gelegenheit für einen Konzerner, sein Einkommen \"ein wenig\" aufzubessern. Er hat die Ware, er hat kein Gewissen... und bislang noch kein Team, das ihm hilft, die heiße Fracht an einen zahlungskräftigen Kunden zu bringen. Vorzugsweise ohne zu sterben.",
	"edition": 6,
	"publisher": ["Pegasus Spiele"],
	"releaseDate": ["2025-06-04"],
	"gameDate": "2082-01",
	"status": "missing",
	"cover": "./cover.jpg"
}
