=== madcampos/sdrlog/src/data/$schemas/data.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "7a61ffa0-4170-47ba-994d-1e470412c8ad",
	"type": "object",
	"required": ["category", "type", "sku", "name", "description", "edition", "publisher", "originalLanguage", "gameDate", "status", "cover"],
	"definitions": {
		"locale-code": {
			"type": "string",
			"pattern": "^(?:art-lojban|cel-gaulish|no-bok|no-nyn|zh-guoyu|zh-hakka|zh-min|zh-min-nan|zh-xiang|en-GB-oed|i-ami|i-bnn|i-default|i-enochian|i-hak|i-klingon|i-lux|i-mingo|i-navajo|i-pwn|i-tao|i-tay|i-tsu|sgn-BE-FR|sgn-BE-NL|sgn-CH-DE|(?:x(?:-[A-Za-z0-9]{1,8})+)|(?:(?:(?:[A-Za-z]{2,3}(?:-[A-Za-z]{3}(?:-[A-Za-z]{3}){0,2})?)|[A-Za-z]{4}|[A-Za-z]{5,8})(?:-[A-Za-z]{4})?(?:-[A-Za-z]{2}|[0-9]{3})?(?:-[A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3})*(?:-[0-9A-WY-Za-wy-z](?:-[A-Za-z0-9]{2,8})+)*(?:-x(?:-[A-Za-z0-9]{1,8})+)?))$"
		},
		"sku": { "type": "string", "pattern": "^[A-Z0-9](?:-?[A-Z0-9])+(?:-[A-Z])?$" },
		"publisher": {
			"enum": [
				"Catalyst Game Labs",
				"Cliffhanger Productions",
				"FASA Corporation",
				"Fantasy Productions",
				"Harebrained Schemes",
				"Pegasus Spiele",
				"WizKids Games",
				"Heyne Verlag",
				"Other",
				"Unofficial"
			]
		},
		"absolute-link": { "type": "string", "format": "uri" },
		"relative-link": { "type": "string", "format": "iri" },
		"category": { "enum": ["rulebook", "sourcebook", "mission", "magazine", "novel", "videogame", "tcg", "boardgame", "misc"] },
		"type": { "enum": ["digital", "print", "scan", "ocr", "physical"] },
		"sku-list": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "$ref": "#/definitions/sku" } },
		"name": { "type": "string" },
		"names": { "type": "object", "propertyNames": { "$ref": "#/definitions/locale-code" }, "additionalProperties": { "type": "string", "minLength": 1 }, "minProperties": 1 },
		"description": { "type": "string", "minLength": 1 },
		"edition": { "type": "integer", "minimum": 1, "maximum": 6 },
		"publisher-list": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "$ref": "#/definitions/publisher" } },
		"game-date": { "type": "string", "pattern": "^[0-9]{4}-[0-9]{2}$" },
		"release-date": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "type": "string", "format": "date" } },
		"status": { "enum": ["missing", "outofscope", "canceled", "ok", "partially-missing"] },
		"original-language": { "$ref": "#/definitions/locale-code" },
		"notes": { "type": "string", "minLength": 1 },
		"links": { "type": "object", "propertyNames": { "$ref": "#/definitions/absolute-link" }, "additionalProperties": { "type": "string", "minLength": 1 }, "minProperties": 1 }
	},
	"properties": {
		"category": { "$ref": "#/definitions/category" },
		"type": { "$ref": "#/definitions/type" },
		"sku": { "$ref": "#/definitions/sku-list" },
		"name": { "$ref": "#/definitions/name" },
		"names": { "$ref": "#/definitions/names" },
		"description": { "$ref": "#/definitions/description" },
		"edition": { "$ref": "#/definitions/edition" },
		"publisher": { "$ref": "#/definitions/publisher-list" },
		"gameDate": { "$ref": "#/definitions/game-date" },
		"releaseDate": { "$ref": "#/definitions/release-date" },
		"status": { "$ref": "#/definitions/status" },
		"originalLanguage": { "$ref": "#/definitions/original-language" },
		"notes": { "$ref": "#/definitions/notes" },
		"links": { "$ref": "#/definitions/links" },
		"subItems": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"name": { "$ref": "#/definitions/name" },
					"status": { "$ref": "#/definitions/status" },
					"description": { "$ref": "#/definitions/description" },
					"notes": { "$ref": "#/definitions/notes" },
					"links": { "$ref": "#/definitions/links" }
				}
			}
		},
		"cover": { "$ref": "#/definitions/relative-link" }
	}
}

=== madcampos/sdrlog/public/data/5496/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["5496", "27806"],
	"name": "Worlds Without End",
	"category": "novel",
	"type": "digital",
	"names": { "de-DE": "Die endlosen Welten" },
	"originalLanguage": "en-US",
	"description": "Spawned in the realm between the worlds, a Horror comes.\nDefeated in battle centuries before by the elven mage Aina, it walks again, seeking vengeance on the mortal lands.\nIf Aina fails to convince the courts of Tir na nOg and Tir Tairngire of the danger, she will have to face the Horror alone once more--or watch the world end.\n<small>NOTE: This story was originally written to conclude the Immortals trilogy; of which the first two parts were <em>Earthdawn</em> novels still unpublished at the time. <strong><em>Scars</em></strong> was published in 2005, and <strong><em>Little Treasures</em></strong> remains unpublished in English.</small>",
	"edition": 2,
	"publisher": ["FASA Corporation", "Catalyst Game Labs", "Heyne Verlag"],
	"releaseDate": ["1995-10-01", "2003-06-01"],
	"gameDate": "2056-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/5427/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["5427"],
	"name": "Nosferatu",
	"category": "novel",
	"type": "digital",
	"names": { "de-DE": "Nosferatu 2055" },
	"originalLanguage": "en-US",
	"description": "Mage and part-time shadowrunner Serrin Shamander and his companions desperately flee a relentless, demonic enemy out to eliminate humankind from the face of the earth. This is the 2nd book with renegade elven mage Serrin Shamander and British Lord Geraint Llanfrechfa.",
	"edition": 2,
	"publisher": ["FASA Corporation", "Catalyst Game Labs", "Heyne Verlag"],
	"releaseDate": ["1994-08-01", "2003-06-01"],
	"gameDate": "2053-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/FN2509/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["FN2509"],
	"name": "Calaveras and Chrome",
	"category": "novel",
	"type": "digital",
	"originalLanguage": "en-US",
	"description": "## WHEN THE RUN IS TOO GOOD TO BE TRUE…\n\nThe decker known as Riposte lives by the rule of “trust, but verify.” And when a promising shadowrun with a big payday sends up a red flag, he does a little shadow snooping of his own to find out what the real deal is.\n\nHis investigation leads him down some dark streets, but there’s no concrete evidence he can find before the run goes down. Paired with an ork street samurai and an elven mage, Riposte will need all his skill to finish the run, get out alive…and get paid…",
	"edition": 6,
	"publisher": ["Catalyst Game Labs"],
	"releaseDate": ["2025-10-01"],
	"gameDate": "2082-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/26405/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["26405"],
	"name": "Horizon Adventure 1: A Fistful of Credsticks",
	"category": "mission",
	"type": "digital",
	"originalLanguage": "en-US",
	"description": "Nothing's as simple as it seems—any runner knows that. So what seems like a simple job guarding some precious cargo on the set of a trideo shoot is bound to get complicated. And it does—but are you ready to travel the full length the long, twisted road ahead? A Fistful of Credsticks begins a new series of adventures centered on the machinations of the Horizon Corporation. Runners will learn more about the dark side of Horizon, leading to future developments that could change the shape of the entire corporation. Runners that see this adventure to the finish will encounter trideo makers, music celebrities, showbiz leeches, some gang members bent on fame, and a very peculiar corporate experiment.",
	"edition": 4,
	"publisher": ["Catalyst Game Labs"],
	"releaseDate": ["2011-04-01"],
	"gameDate": "2072-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/27511/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["27511", "45049"],
	"name": "Sixth World Tarot",
	"category": "misc",
	"type": "print",
	"names": { "de-DE": "Tarot der Sechsten Welt" },
	"originalLanguage": "en-US",
	"description": "The Sixth World Tarot Deck for Shadowrun is much more than just a tarot deck. Created by Echo and Lazarus Chernik for Catalyst Game Labs, the deck is a multi-tiered, masterfully illustrated game accessory for Shadowrun, Fifth Edition, and includes hundreds of puzzles, plots, and enigmas that can be at the heart of compelling campaigns. The Sixth World Tarot comes complete with 78 full-color tarot cards and a guidebook. The cards are 2.5' x 5' tall, with gilded edges.",
	"edition": 5,
	"publisher": ["Catalyst Game Labs", "Pegasus Spiele"],
	"releaseDate": ["2016-01-01"],
	"gameDate": "2075-01",
	"status": "outofscope",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/10665/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["10665", "10760"],
	"name": "Survival of the Fittest",
	"category": "mission",
	"type": "scan",
	"names": { "de-DE": "Fressen oder gefressen werden" },
	"originalLanguage": "en-US",
	"description": "Ancient Tradition Violated...\n\nA New Order Declared...\n\nThe death of the great dragon Dunkelzahn kicked off a series of events that are only now reaching climax. A challenge is declared as antediluvian customs clash with the methods of the modern world. The shadowrunners are involved in a string of unrelated missions that begin to tie themselves together. From the ruins of Tehran to the jungles of Amazonia, from the towers of Hong Kong to the deep metaplanes, the machinations of a reptilian chess game begin to unfold.\nSurvival of the Fittest is a series of seven adventures that can be played consecutively or interwoven into an existing campaign.",
	"edition": 3,
	"publisher": ["Fantasy Productions"],
	"releaseDate": ["2004-05-01"],
	"gameDate": "2062-06",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/45068/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["45068"],
	"name": "Hamburg - Zusatzpack",
	"category": "sourcebook",
	"type": "digital",
	"originalLanguage": "de-DE",
	"description": "Manchmal reicht es nicht, alle Informationen zu besitzen. Manchmal muss es einfach mehr sein. Manchmal muss man mit den Informationen spielen können, sie praktisch nutzen, tiefer in etwas eintauchen. Das gilt nicht nur für die Schatten der Sechsten Welt, es gilt auch für den heimatlichen Spieltisch. Hamburg, der Megaplex an der Elbe, ist ein Spielplatz für Runner, der mehr verlangt und deswegen auch mehr bietet. Damit man noch weiter unter die Oberfläche des dunklen und allgegenwärtigen Wassers des Venedigs an der Elbe vordringen kann.\nDer Zusatzpack zu Hamburg für Shadowrun 5 bietet nicht nur einen speziellen Spielleiterschirm. Es liefert zudem einen Kurzroman zur Stadt, eine Inplay-Werbebroschüre für Runner und andere Schattentouristen, mehr als zwanzig Charaktere aus dem Sprawl mit Bild und Spielwerten auf praktischen Karteiblättern, kleinere Übersichtskarten zu Gangaktivitäten, der Innenstadt und dem öffentlichen Nahverkehr sowie Daten für den Download eines ganz besonderen Soundtracks. So haben Runner Hamburg noch nie erlebt.",
	"edition": 5,
	"publisher": ["Pegasus Spiele"],
	"releaseDate": ["2018-10-07"],
	"gameDate": "2078-01",
	"notes": "Complementary material to Datapuls: Hamburg, contains maps, booklets and a GM Screen.",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/SOK207/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["SOK207"],
	"name": "Shadowland #7",
	"category": "magazine",
	"type": "ocr",
	"originalLanguage": "en-US",
	"description": "The cover is not included in the page numbers.\nIndex:\nFront page (Mark Nelson)\n1 Index & Credits\n2 Download (Editorial - Chris Hussey)\n3 Expect the Unexpected (Fiction - Andrew Hamilton)\n6 Getting Physical (Physical Adept powers - Ken Sato)\n7 Friendship & Honor (Fiction - Steven Warnock)\n12 Gen Con Wrap-up\n13 Technobabel (Preview - Steven Kenson)\n15 Cyberpirates Preview\n17 The Knight Shift (Prime Runners - Unknown)\n28 The New Tools of Anti-Social Behavior (Firearms - Brian Downes)\n31 Gotcha! (Hit locations - Ben Zitterkoph, Jason Shockley)\n33 Nature's Shadows (Plant Totems - Anonymous)\n37 Nothing Personal - Just Business (Fiction - Jon Szeto)\n46 Shadowrun CCG List (Mike Mulvihill)\n49 High Noon (Fiction - Jay Fugiel)\n50 Way of the hunter (Physical Adept path, skills & powers - Jonathan Szeto)\n52 Hermetic Lodge (Spells - Chris Hussey)\n54 Newsline (News from the Shadowrun universe)\n55 Writer's Guidelines\n56 Shadowland Disclosure Form",
	"edition": 2,
	"publisher": ["Other"],
	"releaseDate": ["1997-01-01"],
	"gameDate": "2054-01",
	"status": "ok",
	"cover": "./cover.jpg"
}
