=== madcampos/sdrlog/src/data/$schemas/data.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "7a61ffa0-4170-47ba-994d-1e470412c8ad",
	"type": "object",
	"required": ["category", "type", "sku", "name", "description", "edition", "publisher", "originalLanguage", "gameDate", "status", "cover"],
	"definitions": {
		"locale-code": {
			"type": "string",
			"pattern": "^(?:art-lojban|cel-gaulish|no-bok|no-nyn|zh-guoyu|zh-hakka|zh-min|zh-min-nan|zh-xiang|en-GB-oed|i-ami|i-bnn|i-default|i-enochian|i-hak|i-klingon|i-lux|i-mingo|i-navajo|i-pwn|i-tao|i-tay|i-tsu|sgn-BE-FR|sgn-BE-NL|sgn-CH-DE|(?:x(?:-[A-Za-z0-9]{1,8})+)|(?:(?:(?:[A-Za-z]{2,3}(?:-[A-Za-z]{3}(?:-[A-Za-z]{3}){0,2})?)|[A-Za-z]{4}|[A-Za-z]{5,8})(?:-[A-Za-z]{4})?(?:-[A-Za-z]{2}|[0-9]{3})?(?:-[A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3})*(?:-[0-9A-WY-Za-wy-z](?:-[A-Za-z0-9]{2,8})+)*(?:-x(?:-[A-Za-z0-9]{1,8})+)?))$"
		},
		"sku": { "type": "string", "pattern": "^[A-Z0-9](?:-?[A-Z0-9])+(?:-[A-Z])?$" },
		"publisher": {
			"enum": [
				"Catalyst Game Labs",
				"Cliffhanger Productions",
				"FASA Corporation",
				"Fantasy Productions",
				"Harebrained Schemes",
				"Pegasus Spiele",
				"WizKids Games",
				"Heyne Verlag",
				"Other",
				"Unofficial"
			]
		},
		"absolute-link": { "type": "string", "format": "uri" },
		"relative-link": { "type": "string", "format": "iri" },
		"category": { "enum": ["rulebook", "sourcebook", "mission", "magazine", "novel", "videogame", "tcg", "boardgame", "misc"] },
		"type": { "enum": ["digital", "print", "scan", "ocr", "physical"] },
		"sku-list": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "$ref": "#/definitions/sku" } },
		"name": { "type": "string" },
		"names": { "type": "object", "propertyNames": { "$ref": "#/definitions/locale-code" }, "additionalProperties": { "type": "string", "minLength": 1 }, "minProperties": 1 },
		"description": { "type": "string", "minLength": 1 },
		"edition": { "type": "integer", "minimum": 1, "maximum": 6 },
		"publisher-list": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "$ref": "#/definitions/publisher" } },
		"game-date": { "type": "string", "pattern": "^[0-9]{4}-[0-9]{2}$" },
		"release-date": { "type": "array", "minItems": 1, "uniqueItems": true, "items": { "type": "string", "format": "date" } },
		"status": { "enum": ["missing", "outofscope", "canceled", "ok", "partially-missing"] },
		"original-language": { "$ref": "#/definitions/locale-code" },
		"notes": { "type": "string", "minLength": 1 },
		"links": { "type": "object", "propertyNames": { "$ref": "#/definitions/absolute-link" }, "additionalProperties": { "type": "string", "minLength": 1 }, "minProperties": 1 }
	},
	"properties": {
		"category": { "$ref": "#/definitions/category" },
		"type": { "$ref": "#/definitions/type" },
		"sku": { "$ref": "#/definitions/sku-list" },
		"name": { "$ref": "#/definitions/name" },
		"names": { "$ref": "#/definitions/names" },
		"description": { "$ref": "#/definitions/description" },
		"edition": { "$ref": "#/definitions/edition" },
		"publisher": { "$ref": "#/definitions/publisher-list" },
		"gameDate": { "$ref": "#/definitions/game-date" },
		"releaseDate": { "$ref": "#/definitions/release-date" },
		"status": { "$ref": "#/definitions/status" },
		"originalLanguage": { "$ref": "#/definitions/original-language" },
		"notes": { "$ref": "#/definitions/notes" },
		"links": { "$ref": "#/definitions/links" },
		"subItems": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"name": { "$ref": "#/definitions/name" },
					"status": { "$ref": "#/definitions/status" },
					"description": { "$ref": "#/definitions/description" },
					"notes": { "$ref": "#/definitions/notes" },
					"links": { "$ref": "#/definitions/links" }
				}
			}
		},
		"cover": { "$ref": "#/definitions/relative-link" }
	}
}

=== madcampos/sdrlog/public/data/481D3/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["481D3"],
	"name": "Datapuls: Kunstraub",
	"category": "sourcebook",
	"type": "digital",
	"originalLanguage": "de-DE",
	"description": "Schatzjäger der neuen Zeit\n\nNicht nur in Hochsicherheitslaboren und in den Datenspeichern der Großkonzerne wartet auf findige Shadowrunner interessante Beute: Auch in Museen, Galerien und privaten Kunstsammlungen warten wahre Schätze. Ob ein Gemälde von Picasso, eine uralte römische Münze oder eine hochmoderne AR-Installation - wer es zu stehlen weiß und den richtigen Hehler kennt, der kann reich werden. Und wer den Falschen bestiehlt oder nicht aufpasst, wird begraben.\n\nDatapuls Kunstraub wirft ein Licht auf ein großes Feld von Shadowruns: Diebstähle von Kunstobjekten. Es liefert einen Einblick in die unterschiedlichen Strategien, bietet Grundrisse von Museen und Galerien und beschreibt den illegalen Kunstmarkt der ADL. Zudem wird die Preußenstiftung als wichtiger Schattenspieler und Auftraggeber beschrieben.",
	"edition": 6,
	"publisher": ["Pegasus Spiele"],
	"releaseDate": ["2021-02-18"],
	"gameDate": "2080-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/5712/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["5712"],
	"name": "Wolf & Raven",
	"category": "novel",
	"type": "digital",
	"names": { "de-DE": "Wolf & Rabe" },
	"originalLanguage": "en-US",
	"description": "The adventures of Wolfgang Kies, soldier of fortune. Together with a group of cyborg bounty hunters and computer wizards, he assists elf lord Dr. Richard Raven in keeping humanity safe from preying monstersâ€”both magical and technological! But crime lord Etienne LaPlante interferes with their vigilantism, preparing to strike at Raven and those who serve him....",
	"edition": 3,
	"publisher": ["FASA Corporation", "Catalyst Game Labs", "Heyne Verlag"],
	"releaseDate": ["1998-07-01", "2003-06-01"],
	"gameDate": "2060-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/45067/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["45067"],
	"name": "Ebbe und Flut",
	"category": "mission",
	"type": "digital",
	"originalLanguage": "de-DE",
	"description": "Hamburg kennt viele Arten von Wasser. Trübes Wasser, Brackwasser, steigendes und fallendes Wasser. Giftiges Wasser. Und in den wenigsten lauert etwas Gutes. Wer im Sprawl an der Waterkant Runs durchführt und in seinen Schatten Geld verdienen möchte, sollte auf nasse Überraschungen vorbereitet sein: auf dunkle Geheimnisse im Watt und auf Verfolgungsjagden durch die Kanäle von Wildost. Aber auch an Land warten Bedrohungen - selbst hinter den Kulissen der allgegenwärtigen Vergnügungen.\nEbbe und Flut ist ein Abenteuerband mit drei Abenteuern für Shadowrun 5, die in die Schatten Hamburgs führen. Die Runner begleiten Combat-Golfer bei Hole in One, untersuchen merkwürdige Vorkommnisse An der Nordseeküste und erleben Abenteuer Im Schatten der Scheinwerfer. Alle Abenteuer sind komplett spielfertig, inklusive Grundrisszeichnungen und Pläne. Es handelt sich um eine Eigenproduktion von Pegasus Press.",
	"edition": 5,
	"publisher": ["Pegasus Spiele"],
	"releaseDate": ["2018-10-07"],
	"gameDate": "2075-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/7105/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["7105", "10713"],
	"name": "Paranormal Animals of North America",
	"category": "sourcebook",
	"type": "scan",
	"names": { "de-DE": "Handbuch der Erwachten Wesen: Band 1 Nordamerika" },
	"originalLanguage": "en-US",
	"description": "Lions, Tigers, and Bearsâ€¦\nYou Should Be So Lucky.\nMagic has returned to the world, and with it has come all manner of beasts. Genetic material, long dormant with the absence of magic, has been reactivated, transforming mundane animals into creatures once believed supernatural, even mythical. Juggernauts rome the plains, Firedrakes infest the woods, Leviathans swim in the oceans, and Devil Rats now hunt Man in the shattered Sprawls that he has created.",
	"edition": 1,
	"publisher": ["FASA Corporation", "Fantasy Productions", "Catalyst Game Labs"],
	"releaseDate": ["1990-06-01", "1994-01-01", "2005-08-26"],
	"gameDate": "2051-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/5310/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["5310", "27803"],
	"name": "Night's Pawn",
	"category": "novel",
	"type": "digital",
	"names": { "de-DE": "Spielball der Nacht" },
	"originalLanguage": "en-US",
	"description": "For years, Jason Chase was at the head of the pack, shadowrunning with the best in the business. When time dulled his flesh and cybernetic edge, he knew it was time to get out, or get dead.\nNow, his past has come back to haunt him. To protect a young girl from the terrorists who want her dead, Chase must rely on his years of experience, and whatever his body has left to give. And everything he's got, he'll need as he comes face-to-face with a part of his life he thought he'd left behind, and an enemy left for dead.",
	"edition": 2,
	"publisher": ["FASA Corporation", "Catalyst Game Labs", "Heyne Verlag"],
	"releaseDate": ["1993-04-01", "2003-06-01"],
	"gameDate": "2053-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/483DA2/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["483DA2"],
	"name": "Datapuls: SOTA 2083",
	"category": "sourcebook",
	"type": "digital",
	"originalLanguage": "de",
	"description": "Neue Ausrüstung braucht das Land\n\nMag auch die Welt untergehen: Es braucht schon etwas mehr, um Konzerne daran zu hindern, neue Tech auf den Markt zu werfen. Vom fliegenden BMW-Sportwagen über das schwimmfähige Quad bis zur Hightech-Maikäfer-Drohne liefert dir dieser Datapuls alles, was die 2082er-Messen für 2083 angekündigt haben. Plus SR6-Werte für Plex-Cabs, oTTo-Trolltaxis, Proteus-Mini-U-Boote und vieles mehr.",
	"edition": 6,
	"publisher": ["Pegasus Spiele"],
	"releaseDate": ["2024-03-28"],
	"gameDate": "2082-01",
	"status": "missing",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/3890645704/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["3890645704"],
	"name": "Elementares Wissen",
	"category": "novel",
	"type": "digital",
	"originalLanguage": "de-DE",
	"description": "Das Runnerteam Pik-Dame existiert nicht mehr. Paul, Pandora, Claw, Zack, Snap und Chet gehen längst ihre eigenen Wege. Doch dann taucht eine alte Bedrohung aus der gemeinsamen Vergangenheit auf und zwingt die Runner, sich wieder zusammenzuschließen. Die Feinde sind heute mächtiger als je zuvor — und es gibt sogar Anzeichen dafür, dass ein Verräter in den eigenen Reihen lauert.\n\nElementares Wissen ist der Abschluss und Höhepunkt von Harri Aßmanns Nordlichter-Trilogie.",
	"edition": 2,
	"publisher": ["Heyne Verlag"],
	"releaseDate": ["2002-01-01", "2004-01-01"],
	"gameDate": "2050-01",
	"status": "ok",
	"cover": "./cover.jpg"
}

=== madcampos/sdrlog/public/data/481D2/index.json
{
	"$schema": "../$schemas/data.schema.json",
	"sku": ["481D2"],
	"name": "Datapuls: Magische Orte",
	"category": "sourcebook",
	"type": "digital",
	"originalLanguage": "de-DE",
	"description": "Alte Geister, neue Mächte\n\nWo die Magie zum Leben erwacht und mit ihr die vergessenen Mythen, die dunklen Geheimnisse und die finsteren Kulte der Vergangenheit, da werden friedliche Orte und Touristenziele plötzlich zu magischen Hotspots. In der Sechsten Welt verändert sich alles - und so werden aus alten Gemäuern Spukhäuser, aus Sagengestalten echte Geister und aus alten Geschichten Wahrheiten, die einen Nachts in finsteren Träumen jagen.\n\nDatapuls Magische Orte wirft ein Licht auf unterschiedliche Orte der ADL, die nach Wiederkehren der Magie zu neuem Leben erwacht sind: Naturplätzen wie die Atta-Höhle, alte Ritualorte wie das Ringheiligtum von Pömmelte und Mythen der neueren Geschichte wie die Pfaueninsel. Mehr als zwanzig solcher magischen Plätze in der ADL, Österreich und der Schweiz werden beschrieben - einige mit Grundriss - und können als Schauplatz für Szenen oder ganze Runs dienen.",
	"edition": 6,
	"publisher": ["Pegasus Spiele"],
	"releaseDate": ["2021-02-18"],
	"gameDate": "2080-01",
	"status": "ok",
	"cover": "./cover.jpg"
}
